FROM jimador/docker-jdk-8-maven-node

MAINTAINER Igor Konovalov "rogee.nok@gmail.com"

COPY client ./home/nc-app/src/client
COPY server ./home/nc-app/src/server
COPY pom.xml ./home/nc-app/src/

# MAKE BUILD SRC
# --------------
RUN mvn -f ./home/nc-app/src/pom.xml clean package

# MAKE fat jar as volume
# --------------
# --create volume here--